version: "3.8"

services:
  # switch to mariadb
  db:
    image: postgres:9
    user: postgres
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # TODO set ENV for time difference -8
  # HTTPS http://localhost:8080/index.php/admin/globalsettings#security
  # IP whitelist for login:
  app:
    # image: acspri/limesurvey
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    hostname: crs.devel
    # https://social.msdn.microsoft.com/Forums/azure/en-US/429f90c3-166b-480a-8b2f-ed9752373e18/smtp-service-on-azure?forum=WAVirtualMachinesVirtualNetwork
    #
    # TODO set outgoing smtp port to dynamically map
    ports:
      - 8080:8080
      - 587:587
    # http://localhost:8080/index.php/admin/authentication/sa/login
    environment:
      DB_TYPE: ${DB_TYPE}
      POSTGRESQL_DB_HOST: ${DB_HOST}
      POSTGRESQL_PORT: ${DB_PORT}
      POSTGRESQL_DB_NAME: ${DB_NAME}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      DB_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      SITENAME: ${SITENAME}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      BOUNCE_EMAIL: ${BOUNCE_EMAIL}
      EMAIL_PROTOCOL: ${EMAIL_PROTOCOL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SSL: ${SMTP_SSL}
      SMTP_DEBUG: ${SMTP_DEBUG:-0} # 1 for debug
      EMAIL_MAX: ${EMAIL_MAX:-50} # Per batch
      APACHE_RUN_USER: default_user
      APACHE_RUN_GROUP: root
      #
      DEBUG_APP: ${DEBUG_APP:-0} # 2 for STRICT PHP errors
      DEBUG_SQL: ${DEBUG_SQL:-0} # 1, active onlywhen DEBUG_APP=2
    volumes:
      - ./backend/plugins:/var/www/html/plugins:delegated
      - ./backend/upload:/var/www/html/upload:delegated
      - ./backend/config:/var/www/html/application/config:delegated
    depends_on:
      - db
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "dockerize -wait tcp://${DB_HOST}:${DB_PORT} -timeout 30s -- docker-entrypoint.sh apache2-foreground",
      ]
